#DOcker compose file
# Use NextJS for main app and add postgre as database.

version: '3.8'

services:
  web:
    build: .
    env_file: 
        - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
