version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=collaro
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  collaro-app:
    build: .
    container_name: collaro-container
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/collaro
    depends_on:
      - postgres

volumes:
  postgres:

