name: collaro

services:
  collaro-db:
    image: postgres:16.2
    container_name: collaro-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - collaro-network

  collaro-app:
    image: coderx85/collaro:latest
    container_name: collaro
    restart: unless-stopped
    build:
      context: .
      args:
        - DATABASE_URL=postgres://postgres:postgres@collaro-db:5432/postgres
        - NEXT_PUBLIC_APP_URL=http://localhost:3000
        - NEXT_PUBLIC_BETTER_AUTH_URL=http://localhost:3000
    env_file:
      - .env.production
    environment:
      - DATABASE_URL=postgres://postgres:postgres@collaro-db:5432/postgres
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    ports:
      - "4000:3000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      collaro-db:
        condition: service_healthy
    networks:
      - collaro-network

volumes:
  postgres-data:

networks:
  collaro-network:
    driver: bridge
