apiVersion: apps/v1
kind: Deployment
metadata:
  name: collaro-app
  namespace: collaro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: collaro
  template:
    metadata:
      labels:
        app: collaro
    spec:
      containers:
        - name: collaro-container
          image: coderx85/collaro:latest
          ports:
            - containerPort: 3000
          # Resource requests and limits
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          # Health probes
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 15