apiVersion: v1
kind: Secret
metadata:
  name: collaro-secrets
  namespace: collaro
  labels:
    app: collaro
    environment: production
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@collaro-db:5432/postgres"
  BETTER_AUTH_SECRET: "eEUGjFEvwEljPYUl+4ovZQiXbZyWZZ2E7wFDM3JHv8s="
  GITHUB_CLIENT_ID: "Ov23liGWHs2jUkdakM7t"
  GITHUB_CLIENT_SECRET: "c606ac7d96450ce756dcec5bb53bf238cd256c29"
  RESEND_API_KEY: "your_resend_api_key"
  STREAM_SECRET_KEY: "z3xvtkkkxcjkh97xeazg2ap6ypf5gptfvn5vjt7pngugcqp33aj4xfymvq7387zq"
  NEXT_PUBLIC_STREAM_API_KEY: "xxmxkhp7gt24"
  INNGEST_EVENT_KEY: "your_inngest_event_key"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "your_email@gmail.com"
  SMTP_PASS: "your_app_password"
  SMTP_FROM: "Collaro <noreply@collaro.app>"
  DOCKER_TOKEN: "e2oJLN_lhh3J2Zb6NypGy2yXvPg"
