apiVersion: v1
kind: Secret
metadata:
  name: collaro-secrets
  namespace: collaro
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@collaro-db:5432/postgres"
  BETTER_AUTH_SECRET: "change-me"
  GITHUB_CLIENT_ID: "change-me"
  GITHUB_CLIENT_SECRET: "change-me"
  RESEND_API_KEY: "change-me"
  STREAM_SECRET_KEY: "change-me"
  NEXT_PUBLIC_STREAM_API_KEY: "change-me"
  INNGEST_EVENT_KEY: "change-me"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "change-me"
  SMTP_PASS: "change-me"
  SMTP_FROM: "Collaro <noreply@collaro.app>"
  DOCKER_TOKEN: "change-me"
