apiVersion: v1
kind: ServiceAccount
metadata:
  name: collaro
  namespace: collaro
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: collaro
  namespace: collaro
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: collaro
  namespace: collaro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: collaro
subjects:
  - kind: ServiceAccount
    name: collaro
    namespace: collaro
