apiVersion: apps/v1
kind: Deployment
metadata:
  name: collaro-web
  namespace: collaro
  labels:
    app: collaro-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collaro-web
  template:
    metadata:
      labels:
        app: collaro-web
    spec:
      containers:
        - name: web
          image: docker.io/coderx85/collaro:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: collaro-env
          env:
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: DATABASE_URL
              value: "postgresql://user:password@postgres.collaro.svc.cluster.local:5432/mydatabase"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: collaro-web
  namespace: collaro
spec:
  selector:
    app: collaro-web
  ports:
    - port: 80
      targetPort: 3000
      name: http
  type: ClusterIP
